services:
  - type: web
    name: vanich-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn core.wsgi:application --chdir backend --bind 0.0.0.0:8000
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "vanich-backend.onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings

  - type: web
    name: vanich-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://vanich-backend.onrender.com
