# Generated by Django 5.2.1 on 2025-05-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="tel",
            new_name="phone",
        ),
        migrations.AddField(
            model_name="customer",
            name="agree",
            field=models.BooleanField(default=False),
        ),
    ]
