# Generated by Django 5.2.1 on 2025-05-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_rename_tel_customer_phone_customer_agree"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(default="none", max_length=40),
        ),
    ]
