# Generated by Django 5.2.1 on 2025-05-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_product_image_url_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
